spring:
  application:
    name: itoken-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/CloserWU/itoken.git
          search-paths: /itoken-config/respo
          username: CloserWU
          password: ws995339251
  zipkin:
    base-url: http://192.168.233.131:9411
  boot:
    admin:
      client:
        url: http://192.168.233.131:8084

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.233.131:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 注意：此处在视频里是 include: ["health", "info"] 但已无效了，请修改
        include: health,info